import React, { Component } from 'react';
import './index.css';
import AppHeader from './components/AppHeader';
import AppMenu from './components/AppMenu';
import MainChart from './components/MainChart';
import PersonalChart from './components/PersonalChart';


class App extends Component {
    constructor(){
      super()
      this.state = 
      {
        students:[
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'SCRUM', difficulty:'3', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W1D1-1', difficulty:'3', likeability:'3'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W1D2-1', difficulty:'1', likeability:'3'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W1D2-2', difficulty:'1', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W1D2-3', difficulty:'2', likeability:'3'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W1D2-4', difficulty:'3', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W1D2-5', difficulty:'3', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W1D3-1', difficulty:'3', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W1D3-2', difficulty:'3', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W1D3-4', difficulty:'4', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W1D3-5', difficulty:'4', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W1D3 - Project - Guess-the-number', difficulty:'5', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W1D4-1', difficulty:'4', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W1D4 - Project - Kleurentoggle', difficulty:'3', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W1D5 - Project -Â Galgje', difficulty:'3', likeability:'3'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W2D1-1', difficulty:'1', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W2D1-2', difficulty:'2', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W2D2-1', difficulty:'3', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W2D2-2', difficulty:'3', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W2D2-3', difficulty:'3', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W2D3-1', difficulty:'4', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W2D3-2', difficulty:'1', likeability:'3'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W2D3-3', difficulty:'4', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W2D4-1', difficulty:'1', likeability:'3'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W2D4-2', difficulty:'4', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W2D4-3', difficulty:'1', likeability:'3'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W2D5 - Project - Filmzoeker', difficulty:'3', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W3D1-1', difficulty:'3', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W3D1-2', difficulty:'2', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W3D1-3', difficulty:'3', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W3D1-4', difficulty:'3', likeability:'3'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W3D2-1', difficulty:'2', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W3D2-2', difficulty:'3', likeability:'3'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W3D2-3', difficulty:'3', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W3D3-1', difficulty:'4', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W3D3-2', difficulty:'4', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W3D3-3', difficulty:'3', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W3D3-4', difficulty:'4', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W3D4-1', difficulty:'5', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W3D4-2', difficulty:'1', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W3D5 - Project - Todo-List', difficulty:'2', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W4D2-1', difficulty:'1', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W4D2-2', difficulty:'1', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W4D2-3', difficulty:'1', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W4D2-4', difficulty:'1', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W4D3-1', difficulty:'1', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W4D3-2', difficulty:'1', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W4D3-3', difficulty:'1', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W4D3-4', difficulty:'1', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W4D3-5', difficulty:'1', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W4D3 - Project - Next-Level CSS', difficulty:'1', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W5D4-1', difficulty:'3', likeability:'4'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W5D5 - Project - Lil_Playlist', difficulty:'4', likeability:'3'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W6D1-1', difficulty:'5', likeability:'5'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W6D2-1', difficulty:'4', likeability:'3'},
            {name: 'Evelyn', street: 'Dagobertlaan', number: '5', zipcode: '4455DS', city: 'Lopik', phone:'06-44329928', email: 'Evel@hotmail.com', github: 'https://github/eve', assignment: 'W6D2 - Project - Eindopdracht', difficulty:'5', likeability:'5'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'SCRUM', difficulty:'1', likeability:'1'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W1D1-1', difficulty:'4', likeability:'3'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W1D2-1', difficulty:'3', likeability:'1'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W1D2-2', difficulty:'3', likeability:'2'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W1D2-3', difficulty:'4', likeability:'1'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W1D2-4', difficulty:'2', likeability:'3'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W1D2-5', difficulty:'4', likeability:'2'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W1D3-1', difficulty:'3', likeability:'2'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W1D3-2', difficulty:'2', likeability:'1'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W1D3-4', difficulty:'1', likeability:'2'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W1D3-5', difficulty:'4', likeability:'1'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W1D3 - Project - Guess-the-number', difficulty:'2', likeability:'3'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W1D4-1', difficulty:'3', likeability:'2'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W1D4 - Project - Kleurentoggle', difficulty:'4', likeability:'3'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W1D5 - Project -Â Galgje', difficulty:'4', likeability:'1'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W2D1-1', difficulty:'2', likeability:'4'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W2D1-2', difficulty:'4', likeability:'4'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W2D2-1', difficulty:'3', likeability:'4'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W2D2-2', difficulty:'3', likeability:'4'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W2D2-3', difficulty:'1', likeability:'4'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W2D3-1', difficulty:'4', likeability:'3'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W2D3-2', difficulty:'4', likeability:'1'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W2D3-3', difficulty:'1', likeability:'1'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W2D4-1', difficulty:'1', likeability:'4'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W2D4-2', difficulty:'2', likeability:'3'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W2D4-3', difficulty:'2', likeability:'3'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W2D5 - Project - Filmzoeker', difficulty:'2', likeability:'2'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W3D1-1', difficulty:'4', likeability:'2'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W3D1-2', difficulty:'3', likeability:'2'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W3D1-3', difficulty:'1', likeability:'4'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W3D1-4', difficulty:'1', likeability:'3'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W3D2-1', difficulty:'1', likeability:'3'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W3D2-2', difficulty:'2', likeability:'3'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W3D2-3', difficulty:'2', likeability:'3'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W3D3-1', difficulty:'2', likeability:'2'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W3D3-2', difficulty:'4', likeability:'3'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W3D3-3', difficulty:'3', likeability:'3'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W3D3-4', difficulty:'1', likeability:'3'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W3D4-1', difficulty:'1', likeability:'1'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W3D4-2', difficulty:'3', likeability:'2'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W3D5 - Project - Todo-List', difficulty:'1', likeability:'1'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W4D2-1', difficulty:'2', likeability:'1'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W4D2-2', difficulty:'3', likeability:'2'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W4D2-3', difficulty:'2', likeability:'2'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W4D2-4', difficulty:'3', likeability:'4'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W4D3-1', difficulty:'2', likeability:'1'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W4D3-2', difficulty:'4', likeability:'4'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W4D3-3', difficulty:'3', likeability:'1'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W4D3-4', difficulty:'3', likeability:'1'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W4D3-5', difficulty:'4', likeability:'3'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W4D3 - Project - Next-Level CSS', difficulty:'4', likeability:'4'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W5D4-1', difficulty:'1', likeability:'3'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W5D5 - Project - Lil_Playlist', difficulty:'3', likeability:'2'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W6D1-1', difficulty:'1', likeability:'1'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W6D2-1', difficulty:'2', likeability:'2'},
            {name: 'Aranka', street: 'Kamperfoeliepad', number: '462', zipcode: '1355SK', city: 'Den Boch', phone:'06-654654628', email: 'ArankaEvel@gmail.com', github: '', assignment: 'W6D2 - Project - Eindopdracht', difficulty:'3', likeability:'4'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'SCRUM', difficulty:'2', likeability:'1'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W1D1-1', difficulty:'4', likeability:'3'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W1D2-1', difficulty:'1', likeability:'2'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W1D2-2', difficulty:'1', likeability:'4'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W1D2-3', difficulty:'1', likeability:'4'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W1D2-4', difficulty:'3', likeability:'4'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W1D2-5', difficulty:'1', likeability:'3'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W1D3-1', difficulty:'2', likeability:'4'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W1D3-2', difficulty:'4', likeability:'4'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W1D3-4', difficulty:'4', likeability:'2'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W1D3-5', difficulty:'2', likeability:'4'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W1D3 - Project - Guess-the-number', difficulty:'2', likeability:'2'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W1D4-1', difficulty:'1', likeability:'3'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W1D4 - Project - Kleurentoggle', difficulty:'4', likeability:'3'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W1D5 - Project -Â Galgje', difficulty:'4', likeability:'4'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W2D1-1', difficulty:'2', likeability:'2'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W2D1-2', difficulty:'4', likeability:'1'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W2D2-1', difficulty:'4', likeability:'1'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W2D2-2', difficulty:'2', likeability:'2'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W2D2-3', difficulty:'4', likeability:'2'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W2D3-1', difficulty:'1', likeability:'1'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W2D3-2', difficulty:'1', likeability:'2'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W2D3-3', difficulty:'3', likeability:'3'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W2D4-1', difficulty:'4', likeability:'4'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W2D4-2', difficulty:'3', likeability:'1'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W2D4-3', difficulty:'4', likeability:'1'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W2D5 - Project - Filmzoeker', difficulty:'4', likeability:'1'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W3D1-1', difficulty:'4', likeability:'3'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W3D1-2', difficulty:'2', likeability:'3'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W3D1-3', difficulty:'2', likeability:'3'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W3D1-4', difficulty:'3', likeability:'3'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W3D2-1', difficulty:'3', likeability:'2'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W3D2-2', difficulty:'2', likeability:'2'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W3D2-3', difficulty:'3', likeability:'2'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W3D3-1', difficulty:'4', likeability:'4'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W3D3-2', difficulty:'2', likeability:'4'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W3D3-3', difficulty:'2', likeability:'1'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W3D3-4', difficulty:'3', likeability:'2'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W3D4-1', difficulty:'1', likeability:'3'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W3D4-2', difficulty:'2', likeability:'2'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W3D5 - Project - Todo-List', difficulty:'4', likeability:'2'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W4D2-1', difficulty:'1', likeability:'4'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W4D2-2', difficulty:'2', likeability:'3'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W4D2-3', difficulty:'2', likeability:'4'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W4D2-4', difficulty:'1', likeability:'2'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W4D3-1', difficulty:'1', likeability:'4'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W4D3-2', difficulty:'4', likeability:'4'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W4D3-3', difficulty:'3', likeability:'2'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W4D3-4', difficulty:'2', likeability:'2'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W4D3-5', difficulty:'4', likeability:'1'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W4D3 - Project - Next-Level CSS', difficulty:'2', likeability:'2'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W5D4-1', difficulty:'1', likeability:'3'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W5D5 - Project - Lil_Playlist', difficulty:'3', likeability:'1'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W6D1-1', difficulty:'3', likeability:'2'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W6D2-1', difficulty:'1', likeability:'1'},
            {name: 'Floris', street: 'Slingerweg', number: '2', zipcode: '7355SK', city: 'Amsterdam', phone:'06-652526828', email: 'floris43@gmail.com', github: 'github.nl/floris', assignment: 'W6D2 - Project - Eindopdracht', difficulty:'4', likeability:'1'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'SCRUM', difficulty:'1', likeability:'2'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W1D1-1', difficulty:'1', likeability:'4'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W1D2-1', difficulty:'2', likeability:'4'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W1D2-2', difficulty:'2', likeability:'3'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W1D2-3', difficulty:'1', likeability:'2'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W1D2-4', difficulty:'1', likeability:'3'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W1D2-5', difficulty:'3', likeability:'1'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W1D3-1', difficulty:'1', likeability:'4'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W1D3-2', difficulty:'4', likeability:'3'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W1D3-4', difficulty:'3', likeability:'1'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W1D3-5', difficulty:'4', likeability:'2'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W1D3 - Project - Guess-the-number', difficulty:'3', likeability:'1'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W1D4-1', difficulty:'1', likeability:'1'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W1D4 - Project - Kleurentoggle', difficulty:'1', likeability:'3'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W1D5 - Project -Â Galgje', difficulty:'2', likeability:'4'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W2D1-1', difficulty:'4', likeability:'4'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W2D1-2', difficulty:'3', likeability:'2'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W2D2-1', difficulty:'4', likeability:'3'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W2D2-2', difficulty:'1', likeability:'2'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W2D2-3', difficulty:'3', likeability:'2'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W2D3-1', difficulty:'3', likeability:'1'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W2D3-2', difficulty:'4', likeability:'2'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W2D3-3', difficulty:'4', likeability:'2'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W2D4-1', difficulty:'2', likeability:'4'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W2D4-2', difficulty:'4', likeability:'1'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W2D4-3', difficulty:'3', likeability:'2'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W2D5 - Project - Filmzoeker', difficulty:'4', likeability:'1'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W3D1-1', difficulty:'1', likeability:'1'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W3D1-2', difficulty:'1', likeability:'4'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W3D1-3', difficulty:'3', likeability:'2'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W3D1-4', difficulty:'4', likeability:'3'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W3D2-1', difficulty:'1', likeability:'3'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W3D2-2', difficulty:'4', likeability:'3'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W3D2-3', difficulty:'2', likeability:'1'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W3D3-1', difficulty:'4', likeability:'4'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W3D3-2', difficulty:'3', likeability:'1'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W3D3-3', difficulty:'2', likeability:'4'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W3D3-4', difficulty:'4', likeability:'1'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W3D4-1', difficulty:'3', likeability:'4'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W3D4-2', difficulty:'1', likeability:'4'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W3D5 - Project - Todo-List', difficulty:'2', likeability:'4'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W4D2-1', difficulty:'1', likeability:'1'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W4D2-2', difficulty:'2', likeability:'1'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W4D2-3', difficulty:'3', likeability:'3'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W4D2-4', difficulty:'1', likeability:'3'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W4D3-1', difficulty:'3', likeability:'3'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W4D3-2', difficulty:'1', likeability:'4'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W4D3-3', difficulty:'3', likeability:'1'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W4D3-4', difficulty:'1', likeability:'3'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W4D3-5', difficulty:'1', likeability:'2'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W4D3 - Project - Next-Level CSS', difficulty:'3', likeability:'1'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W5D4-1', difficulty:'3', likeability:'4'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W5D5 - Project - Lil_Playlist', difficulty:'3', likeability:'1'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W6D1-1', difficulty:'1', likeability:'1'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W6D2-1', difficulty:'4', likeability:'2'},
            {name: 'Hector', street: 'rondweg', number: '2', zipcode: '5855SK', city: 'Amsterdam', phone:'06-652526828', email: 'Hector3@home.org', github: 'github.nl/floris', assignment: 'W6D2 - Project - Eindopdracht', difficulty:'2', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'SCRUM', difficulty:'1', likeability:'1'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W1D1-1', difficulty:'4', likeability:'1'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W1D2-1', difficulty:'3', likeability:'3'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W1D2-2', difficulty:'2', likeability:'1'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W1D2-3', difficulty:'2', likeability:'1'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W1D2-4', difficulty:'4', likeability:'2'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W1D2-5', difficulty:'3', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W1D3-1', difficulty:'3', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W1D3-2', difficulty:'2', likeability:'1'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W1D3-4', difficulty:'3', likeability:'2'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W1D3-5', difficulty:'1', likeability:'1'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W1D3 - Project - Guess-the-number', difficulty:'2', likeability:'2'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W1D4-1', difficulty:'4', likeability:'2'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W1D4 - Project - Kleurentoggle', difficulty:'1', likeability:'3'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W1D5 - Project -Â Galgje', difficulty:'1', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W2D1-1', difficulty:'1', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W2D1-2', difficulty:'4', likeability:'2'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W2D2-1', difficulty:'4', likeability:'1'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W2D2-2', difficulty:'3', likeability:'3'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W2D2-3', difficulty:'3', likeability:'1'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W2D3-1', difficulty:'4', likeability:'2'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W2D3-2', difficulty:'3', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W2D3-3', difficulty:'3', likeability:'3'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W2D4-1', difficulty:'1', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W2D4-2', difficulty:'3', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W2D4-3', difficulty:'3', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W2D5 - Project - Filmzoeker', difficulty:'2', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W3D1-1', difficulty:'1', likeability:'1'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W3D1-2', difficulty:'3', likeability:'3'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W3D1-3', difficulty:'3', likeability:'1'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W3D1-4', difficulty:'3', likeability:'2'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W3D2-1', difficulty:'1', likeability:'2'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W3D2-2', difficulty:'2', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W3D2-3', difficulty:'3', likeability:'1'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W3D3-1', difficulty:'1', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W3D3-2', difficulty:'4', likeability:'1'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W3D3-3', difficulty:'3', likeability:'3'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W3D3-4', difficulty:'2', likeability:'3'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W3D4-1', difficulty:'4', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W3D4-2', difficulty:'3', likeability:'1'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W3D5 - Project - Todo-List', difficulty:'2', likeability:'3'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W4D2-1', difficulty:'3', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W4D2-2', difficulty:'1', likeability:'2'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W4D2-3', difficulty:'3', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W4D2-4', difficulty:'4', likeability:'1'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W4D3-1', difficulty:'2', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W4D3-2', difficulty:'1', likeability:'3'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W4D3-3', difficulty:'2', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W4D3-4', difficulty:'4', likeability:'1'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W4D3-5', difficulty:'3', likeability:'2'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W4D3 - Project - Next-Level CSS', difficulty:'3', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W5D4-1', difficulty:'1', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W5D5 - Project - Lil_Playlist', difficulty:'1', likeability:'1'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W6D1-1', difficulty:'2', likeability:'1'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W6D2-1', difficulty:'1', likeability:'4'},
            {name: 'Martina', street: 'nietallesisietslaan', number: '42', zipcode: '4325SK', city: 'Amsterdam', phone:'06-65234353428', email: 'mar543@home.org', github: 'github.nl/mar433',  assignment: 'W6D2 - Project - Eindopdracht', difficulty:'1', likeability:'4'},
            {name: 'Maurits', assignment: 'SCRUM', difficulty:'3', likeability:'4'},
            {name: 'Maurits', assignment: 'W1D1-1', difficulty:'4', likeability:'3'},
            {name: 'Maurits', assignment: 'W1D2-1', difficulty:'2', likeability:'2'},
            {name: 'Maurits', assignment: 'W1D2-2', difficulty:'1', likeability:'4'},
            {name: 'Maurits', assignment: 'W1D2-3', difficulty:'2', likeability:'2'},
            {name: 'Maurits', assignment: 'W1D2-4', difficulty:'3', likeability:'1'},
            {name: 'Maurits', assignment: 'W1D2-5', difficulty:'2', likeability:'3'},
            {name: 'Maurits', assignment: 'W1D3-1', difficulty:'2', likeability:'4'},
            {name: 'Maurits', assignment: 'W1D3-2', difficulty:'2', likeability:'2'},
            {name: 'Maurits', assignment: 'W1D3-4', difficulty:'2', likeability:'2'},
            {name: 'Maurits', assignment: 'W1D3-5', difficulty:'1', likeability:'3'},
            {name: 'Maurits', assignment: 'W1D3 - Project - Guess-the-number', difficulty:'1', likeability:'1'},
            {name: 'Maurits', assignment: 'W1D4-1', difficulty:'3', likeability:'4'},
            {name: 'Maurits', assignment: 'W1D4 - Project - Kleurentoggle', difficulty:'4', likeability:'1'},
            {name: 'Maurits', assignment: 'W1D5 - Project -Â Galgje', difficulty:'3', likeability:'2'},
            {name: 'Maurits', assignment: 'W2D1-1', difficulty:'1', likeability:'1'},
            {name: 'Maurits', assignment: 'W2D1-2', difficulty:'2', likeability:'3'},
            {name: 'Maurits', assignment: 'W2D2-1', difficulty:'1', likeability:'2'},
            {name: 'Maurits', assignment: 'W2D2-2', difficulty:'4', likeability:'1'},
            {name: 'Maurits', assignment: 'W2D2-3', difficulty:'2', likeability:'2'},
            {name: 'Maurits', assignment: 'W2D3-1', difficulty:'2', likeability:'2'},
            {name: 'Maurits', assignment: 'W2D3-2', difficulty:'3', likeability:'3'},
            {name: 'Maurits', assignment: 'W2D3-3', difficulty:'2', likeability:'1'},
            {name: 'Maurits', assignment: 'W2D4-1', difficulty:'1', likeability:'3'},
            {name: 'Maurits', assignment: 'W2D4-2', difficulty:'3', likeability:'2'},
            {name: 'Maurits', assignment: 'W2D4-3', difficulty:'3', likeability:'3'},
            {name: 'Maurits', assignment: 'W2D5 - Project - Filmzoeker', difficulty:'3', likeability:'1'},
            {name: 'Maurits', assignment: 'W3D1-1', difficulty:'4', likeability:'4'},
            {name: 'Maurits', assignment: 'W3D1-2', difficulty:'1', likeability:'3'},
            {name: 'Maurits', assignment: 'W3D1-3', difficulty:'1', likeability:'4'},
            {name: 'Maurits', assignment: 'W3D1-4', difficulty:'1', likeability:'2'},
            {name: 'Maurits', assignment: 'W3D2-1', difficulty:'1', likeability:'4'},
            {name: 'Maurits', assignment: 'W3D2-2', difficulty:'1', likeability:'1'},
            {name: 'Maurits', assignment: 'W3D2-3', difficulty:'4', likeability:'3'},
            {name: 'Maurits', assignment: 'W3D3-1', difficulty:'1', likeability:'1'},
            {name: 'Maurits', assignment: 'W3D3-2', difficulty:'2', likeability:'1'},
            {name: 'Maurits', assignment: 'W3D3-3', difficulty:'1', likeability:'3'},
            {name: 'Maurits', assignment: 'W3D3-4', difficulty:'4', likeability:'1'},
            {name: 'Maurits', assignment: 'W3D4-1', difficulty:'4', likeability:'4'},
            {name: 'Maurits', assignment: 'W3D4-2', difficulty:'1', likeability:'3'},
            {name: 'Maurits', assignment: 'W3D5 - Project - Todo-List', difficulty:'3', likeability:'4'},
            {name: 'Maurits', assignment: 'W4D2-1', difficulty:'3', likeability:'1'},
            {name: 'Maurits', assignment: 'W4D2-2', difficulty:'4', likeability:'4'},
            {name: 'Maurits', assignment: 'W4D2-3', difficulty:'4', likeability:'1'},
            {name: 'Maurits', assignment: 'W4D2-4', difficulty:'2', likeability:'3'},
            {name: 'Maurits', assignment: 'W4D3-1', difficulty:'3', likeability:'1'},
            {name: 'Maurits', assignment: 'W4D3-2', difficulty:'3', likeability:'2'},
            {name: 'Maurits', assignment: 'W4D3-3', difficulty:'3', likeability:'4'},
            {name: 'Maurits', assignment: 'W4D3-4', difficulty:'1', likeability:'3'},
            {name: 'Maurits', assignment: 'W4D3-5', difficulty:'2', likeability:'1'},
            {name: 'Maurits', assignment: 'W4D3 - Project - Next-Level CSS', difficulty:'2', likeability:'3'},
            {name: 'Maurits', assignment: 'W5D4-1', difficulty:'1', likeability:'3'},
            {name: 'Maurits', assignment: 'W5D5 - Project - Lil_Playlist', difficulty:'4', likeability:'2'},
            {name: 'Maurits', assignment: 'W6D1-1', difficulty:'1', likeability:'3'},
            {name: 'Maurits', assignment: 'W6D2-1', difficulty:'1', likeability:'4'},
            {name: 'Maurits', assignment: 'W6D2 - Project - Eindopdracht', difficulty:'3', likeability:'3'},
            {name: 'Rahima', assignment: 'SCRUM', difficulty:'2', likeability:'4'},
            {name: 'Rahima', assignment: 'W1D1-1', difficulty:'3', likeability:'4'},
            {name: 'Rahima', assignment: 'W1D2-1', difficulty:'2', likeability:'4'},
            {name: 'Rahima', assignment: 'W1D2-2', difficulty:'1', likeability:'2'},
            {name: 'Rahima', assignment: 'W1D2-3', difficulty:'1', likeability:'3'},
            {name: 'Rahima', assignment: 'W1D2-4', difficulty:'1', likeability:'2'},
            {name: 'Rahima', assignment: 'W1D2-5', difficulty:'1', likeability:'3'},
            {name: 'Rahima', assignment: 'W1D3-1', difficulty:'1', likeability:'1'},
            {name: 'Rahima', assignment: 'W1D3-2', difficulty:'2', likeability:'4'},
            {name: 'Rahima', assignment: 'W1D3-4', difficulty:'1', likeability:'2'},
            {name: 'Rahima', assignment: 'W1D3-5', difficulty:'2', likeability:'2'},
            {name: 'Rahima', assignment: 'W1D3 - Project - Guess-the-number', difficulty:'3', likeability:'1'},
            {name: 'Rahima', assignment: 'W1D4-1', difficulty:'4', likeability:'3'},
            {name: 'Rahima', assignment: 'W1D4 - Project - Kleurentoggle', difficulty:'2', likeability:'4'},
            {name: 'Rahima', assignment: 'W1D5 - Project -Â Galgje', difficulty:'3', likeability:'3'},
            {name: 'Rahima', assignment: 'W2D1-1', difficulty:'2', likeability:'2'},
            {name: 'Rahima', assignment: 'W2D1-2', difficulty:'3', likeability:'1'},
            {name: 'Rahima', assignment: 'W2D2-1', difficulty:'1', likeability:'1'},
            {name: 'Rahima', assignment: 'W2D2-2', difficulty:'1', likeability:'1'},
            {name: 'Rahima', assignment: 'W2D2-3', difficulty:'4', likeability:'2'},
            {name: 'Rahima', assignment: 'W2D3-1', difficulty:'1', likeability:'1'},
            {name: 'Rahima', assignment: 'W2D3-2', difficulty:'1', likeability:'4'},
            {name: 'Rahima', assignment: 'W2D3-3', difficulty:'4', likeability:'2'},
            {name: 'Rahima', assignment: 'W2D4-1', difficulty:'4', likeability:'4'},
            {name: 'Rahima', assignment: 'W2D4-2', difficulty:'4', likeability:'4'},
            {name: 'Rahima', assignment: 'W2D4-3', difficulty:'2', likeability:'3'},
            {name: 'Rahima', assignment: 'W2D5 - Project - Filmzoeker', difficulty:'3', likeability:'1'},
            {name: 'Rahima', assignment: 'W3D1-1', difficulty:'1', likeability:'1'},
            {name: 'Rahima', assignment: 'W3D1-2', difficulty:'1', likeability:'2'},
            {name: 'Rahima', assignment: 'W3D1-3', difficulty:'2', likeability:'3'},
            {name: 'Rahima', assignment: 'W3D1-4', difficulty:'2', likeability:'4'},
            {name: 'Rahima', assignment: 'W3D2-1', difficulty:'3', likeability:'2'},
            {name: 'Rahima', assignment: 'W3D2-2', difficulty:'1', likeability:'4'},
            {name: 'Rahima', assignment: 'W3D2-3', difficulty:'2', likeability:'1'},
            {name: 'Rahima', assignment: 'W3D3-1', difficulty:'3', likeability:'1'},
            {name: 'Rahima', assignment: 'W3D3-2', difficulty:'4', likeability:'4'},
            {name: 'Rahima', assignment: 'W3D3-3', difficulty:'1', likeability:'4'},
            {name: 'Rahima', assignment: 'W3D3-4', difficulty:'2', likeability:'2'},
            {name: 'Rahima', assignment: 'W3D4-1', difficulty:'1', likeability:'2'},
            {name: 'Rahima', assignment: 'W3D4-2', difficulty:'3', likeability:'3'},
            {name: 'Rahima', assignment: 'W3D5 - Project - Todo-List', difficulty:'2', likeability:'4'},
            {name: 'Rahima', assignment: 'W4D2-1', difficulty:'2', likeability:'4'},
            {name: 'Rahima', assignment: 'W4D2-2', difficulty:'4', likeability:'3'},
            {name: 'Rahima', assignment: 'W4D2-3', difficulty:'3', likeability:'3'},
            {name: 'Rahima', assignment: 'W4D2-4', difficulty:'4', likeability:'1'},
            {name: 'Rahima', assignment: 'W4D3-1', difficulty:'2', likeability:'1'},
            {name: 'Rahima', assignment: 'W4D3-2', difficulty:'1', likeability:'1'},
            {name: 'Rahima', assignment: 'W4D3-3', difficulty:'2', likeability:'1'},
            {name: 'Rahima', assignment: 'W4D3-4', difficulty:'2', likeability:'2'},
            {name: 'Rahima', assignment: 'W4D3-5', difficulty:'3', likeability:'2'},
            {name: 'Rahima', assignment: 'W4D3 - Project - Next-Level CSS', difficulty:'1', likeability:'2'},
            {name: 'Rahima', assignment: 'W5D4-1', difficulty:'3', likeability:'3'},
            {name: 'Rahima', assignment: 'W5D5 - Project - Lil_Playlist', difficulty:'2', likeability:'3'},
            {name: 'Rahima', assignment: 'W6D1-1', difficulty:'4', likeability:'4'},
            {name: 'Rahima', assignment: 'W6D2-1', difficulty:'1', likeability:'4'},
            {name: 'Rahima', assignment: 'W6D2 - Project - Eindopdracht', difficulty:'4', likeability:'1'},
            {name: 'Sandra', assignment: 'SCRUM', difficulty:'4', likeability:'1'},
            {name: 'Sandra', assignment: 'W1D1-1', difficulty:'2', likeability:'4'},
            {name: 'Sandra', assignment: 'W1D2-1', difficulty:'3', likeability:'4'},
            {name: 'Sandra', assignment: 'W1D2-2', difficulty:'3', likeability:'2'},
            {name: 'Sandra', assignment: 'W1D2-3', difficulty:'3', likeability:'4'},
            {name: 'Sandra', assignment: 'W1D2-4', difficulty:'3', likeability:'1'},
            {name: 'Sandra', assignment: 'W1D2-5', difficulty:'4', likeability:'3'},
            {name: 'Sandra', assignment: 'W1D3-1', difficulty:'1', likeability:'1'},
            {name: 'Sandra', assignment: 'W1D3-2', difficulty:'1', likeability:'1'},
            {name: 'Sandra', assignment: 'W1D3-4', difficulty:'3', likeability:'3'},
            {name: 'Sandra', assignment: 'W1D3-5', difficulty:'4', likeability:'3'},
            {name: 'Sandra', assignment: 'W1D3 - Project - Guess-the-number', difficulty:'2', likeability:'4'},
            {name: 'Sandra', assignment: 'W1D4-1', difficulty:'3', likeability:'2'},
            {name: 'Sandra', assignment: 'W1D4 - Project - Kleurentoggle', difficulty:'1', likeability:'3'},
            {name: 'Sandra', assignment: 'W1D5 - Project -Â Galgje', difficulty:'3', likeability:'3'},
            {name: 'Sandra', assignment: 'W2D1-1', difficulty:'4', likeability:'1'},
            {name: 'Sandra', assignment: 'W2D1-2', difficulty:'4', likeability:'3'},
            {name: 'Sandra', assignment: 'W2D2-1', difficulty:'3', likeability:'4'},
            {name: 'Sandra', assignment: 'W2D2-2', difficulty:'2', likeability:'3'},
            {name: 'Sandra', assignment: 'W2D2-3', difficulty:'4', likeability:'3'},
            {name: 'Sandra', assignment: 'W2D3-1', difficulty:'1', likeability:'2'},
            {name: 'Sandra', assignment: 'W2D3-2', difficulty:'3', likeability:'2'},
            {name: 'Sandra', assignment: 'W2D3-3', difficulty:'2', likeability:'2'},
            {name: 'Sandra', assignment: 'W2D4-1', difficulty:'1', likeability:'3'},
            {name: 'Sandra', assignment: 'W2D4-2', difficulty:'2', likeability:'4'},
            {name: 'Sandra', assignment: 'W2D4-3', difficulty:'2', likeability:'2'},
            {name: 'Sandra', assignment: 'W2D5 - Project - Filmzoeker', difficulty:'2', likeability:'4'},
            {name: 'Sandra', assignment: 'W3D1-1', difficulty:'3', likeability:'3'},
            {name: 'Sandra', assignment: 'W3D1-2', difficulty:'3', likeability:'4'},
            {name: 'Sandra', assignment: 'W3D1-3', difficulty:'2', likeability:'4'},
            {name: 'Sandra', assignment: 'W3D1-4', difficulty:'2', likeability:'2'},
            {name: 'Sandra', assignment: 'W3D2-1', difficulty:'2', likeability:'4'},
            {name: 'Sandra', assignment: 'W3D2-2', difficulty:'2', likeability:'3'},
            {name: 'Sandra', assignment: 'W3D2-3', difficulty:'1', likeability:'2'},
            {name: 'Sandra', assignment: 'W3D3-1', difficulty:'1', likeability:'2'},
            {name: 'Sandra', assignment: 'W3D3-2', difficulty:'2', likeability:'2'},
            {name: 'Sandra', assignment: 'W3D3-3', difficulty:'4', likeability:'4'},
            {name: 'Sandra', assignment: 'W3D3-4', difficulty:'3', likeability:'2'},
            {name: 'Sandra', assignment: 'W3D4-1', difficulty:'2', likeability:'3'},
            {name: 'Sandra', assignment: 'W3D4-2', difficulty:'1', likeability:'1'},
            {name: 'Sandra', assignment: 'W3D5 - Project - Todo-List', difficulty:'1', likeability:'2'},
            {name: 'Sandra', assignment: 'W4D2-1', difficulty:'3', likeability:'3'},
            {name: 'Sandra', assignment: 'W4D2-2', difficulty:'1', likeability:'1'},
            {name: 'Sandra', assignment: 'W4D2-3', difficulty:'3', likeability:'4'},
            {name: 'Sandra', assignment: 'W4D2-4', difficulty:'1', likeability:'4'},
            {name: 'Sandra', assignment: 'W4D3-1', difficulty:'3', likeability:'1'},
            {name: 'Sandra', assignment: 'W4D3-2', difficulty:'1', likeability:'3'},
            {name: 'Sandra', assignment: 'W4D3-3', difficulty:'2', likeability:'4'},
            {name: 'Sandra', assignment: 'W4D3-4', difficulty:'1', likeability:'4'},
            {name: 'Sandra', assignment: 'W4D3-5', difficulty:'1', likeability:'3'},
            {name: 'Sandra', assignment: 'W4D3 - Project - Next-Level CSS', difficulty:'3', likeability:'4'},
            {name: 'Sandra', assignment: 'W5D4-1', difficulty:'1', likeability:'1'},
            {name: 'Sandra', assignment: 'W5D5 - Project - Lil_Playlist', difficulty:'2', likeability:'2'},
            {name: 'Sandra', assignment: 'W6D1-1', difficulty:'1', likeability:'4'},
            {name: 'Sandra', assignment: 'W6D2-1', difficulty:'2', likeability:'3'},
            {name: 'Sandra', assignment: 'W6D2 - Project - Eindopdracht', difficulty:'4', likeability:'1'},
            {name: 'Wietske', assignment: 'SCRUM', difficulty:'1', likeability:'1'},
            {name: 'Wietske', assignment: 'W1D1-1', difficulty:'4', likeability:'3'},
            {name: 'Wietske', assignment: 'W1D2-1', difficulty:'1', likeability:'4'},
            {name: 'Wietske', assignment: 'W1D2-2', difficulty:'1', likeability:'2'},
            {name: 'Wietske', assignment: 'W1D2-3', difficulty:'2', likeability:'3'},
            {name: 'Wietske', assignment: 'W1D2-4', difficulty:'2', likeability:'1'},
            {name: 'Wietske', assignment: 'W1D2-5', difficulty:'3', likeability:'4'},
            {name: 'Wietske', assignment: 'W1D3-1', difficulty:'1', likeability:'2'},
            {name: 'Wietske', assignment: 'W1D3-2', difficulty:'1', likeability:'4'},
            {name: 'Wietske', assignment: 'W1D3-4', difficulty:'2', likeability:'1'},
            {name: 'Wietske', assignment: 'W1D3-5', difficulty:'3', likeability:'4'},
            {name: 'Wietske', assignment: 'W1D3 - Project - Guess-the-number', difficulty:'2', likeability:'4'},
            {name: 'Wietske', assignment: 'W1D4-1', difficulty:'2', likeability:'4'},
            {name: 'Wietske', assignment: 'W1D4 - Project - Kleurentoggle', difficulty:'2', likeability:'3'},
            {name: 'Wietske', assignment: 'W1D5 - Project -Â Galgje', difficulty:'3', likeability:'3'},
            {name: 'Wietske', assignment: 'W2D1-1', difficulty:'3', likeability:'1'},
            {name: 'Wietske', assignment: 'W2D1-2', difficulty:'4', likeability:'1'},
            {name: 'Wietske', assignment: 'W2D2-1', difficulty:'2', likeability:'2'},
            {name: 'Wietske', assignment: 'W2D2-2', difficulty:'2', likeability:'4'},
            {name: 'Wietske', assignment: 'W2D2-3', difficulty:'3', likeability:'4'},
            {name: 'Wietske', assignment: 'W2D3-1', difficulty:'2', likeability:'1'},
            {name: 'Wietske', assignment: 'W2D3-2', difficulty:'1', likeability:'1'},
            {name: 'Wietske', assignment: 'W2D3-3', difficulty:'2', likeability:'3'},
            {name: 'Wietske', assignment: 'W2D4-1', difficulty:'1', likeability:'1'},
            {name: 'Wietske', assignment: 'W2D4-2', difficulty:'2', likeability:'4'},
            {name: 'Wietske', assignment: 'W2D4-3', difficulty:'4', likeability:'3'},
            {name: 'Wietske', assignment: 'W2D5 - Project - Filmzoeker', difficulty:'2', likeability:'2'},
            {name: 'Wietske', assignment: 'W3D1-1', difficulty:'1', likeability:'3'},
            {name: 'Wietske', assignment: 'W3D1-2', difficulty:'4', likeability:'4'},
            {name: 'Wietske', assignment: 'W3D1-3', difficulty:'4', likeability:'2'},
            {name: 'Wietske', assignment: 'W3D1-4', difficulty:'1', likeability:'4'},
            {name: 'Wietske', assignment: 'W3D2-1', difficulty:'3', likeability:'2'},
            {name: 'Wietske', assignment: 'W3D2-2', difficulty:'1', likeability:'3'},
            {name: 'Wietske', assignment: 'W3D2-3', difficulty:'2', likeability:'4'},
            {name: 'Wietske', assignment: 'W3D3-1', difficulty:'1', likeability:'4'},
            {name: 'Wietske', assignment: 'W3D3-2', difficulty:'3', likeability:'1'},
            {name: 'Wietske', assignment: 'W3D3-3', difficulty:'1', likeability:'3'},
            {name: 'Wietske', assignment: 'W3D3-4', difficulty:'3', likeability:'4'},
            {name: 'Wietske', assignment: 'W3D4-1', difficulty:'3', likeability:'4'},
            {name: 'Wietske', assignment: 'W3D4-2', difficulty:'4', likeability:'2'},
            {name: 'Wietske', assignment: 'W3D5 - Project - Todo-List', difficulty:'2', likeability:'4'},
            {name: 'Wietske', assignment: 'W4D2-1', difficulty:'3', likeability:'3'},
            {name: 'Wietske', assignment: 'W4D2-2', difficulty:'2', likeability:'4'},
            {name: 'Wietske', assignment: 'W4D2-3', difficulty:'1', likeability:'2'},
            {name: 'Wietske', assignment: 'W4D2-4', difficulty:'4', likeability:'3'},
            {name: 'Wietske', assignment: 'W4D3-1', difficulty:'2', likeability:'1'},
            {name: 'Wietske', assignment: 'W4D3-2', difficulty:'1', likeability:'2'},
            {name: 'Wietske', assignment: 'W4D3-3', difficulty:'1', likeability:'4'},
            {name: 'Wietske', assignment: 'W4D3-4', difficulty:'3', likeability:'4'},
            {name: 'Wietske', assignment: 'W4D3-5', difficulty:'4', likeability:'3'},
            {name: 'Wietske', assignment: 'W4D3 - Project - Next-Level CSS', difficulty:'4', likeability:'2'},
            {name: 'Wietske', assignment: 'W5D4-1', difficulty:'3', likeability:'1'},
            {name: 'Wietske', assignment: 'W5D5 - Project - Lil_Playlist', difficulty:'4', likeability:'2'},
            {name: 'Wietske', assignment: 'W6D1-1', difficulty:'1', likeability:'1'},
            {name: 'Wietske', assignment: 'W6D2-1', difficulty:'2', likeability:'1'},
            {name: 'Wietske', assignment: 'W6D2 - Project - Eindopdracht', difficulty:'1', likeability:'2'},
            {name: 'Storm', assignment: 'SCRUM', difficulty:'1', likeability:'1'},
            {name: 'Storm', assignment: 'W1D1-1', difficulty:'2', likeability:'2'},
            {name: 'Storm', assignment: 'W1D2-1', difficulty:'2', likeability:'3'},
            {name: 'Storm', assignment: 'W1D2-2', difficulty:'1', likeability:'3'},
            {name: 'Storm', assignment: 'W1D2-3', difficulty:'1', likeability:'2'},
            {name: 'Storm', assignment: 'W1D2-4', difficulty:'4', likeability:'3'},
            {name: 'Storm', assignment: 'W1D2-5', difficulty:'3', likeability:'3'},
            {name: 'Storm', assignment: 'W1D3-1', difficulty:'2', likeability:'3'},
            {name: 'Storm', assignment: 'W1D3-2', difficulty:'1', likeability:'1'},
            {name: 'Storm', assignment: 'W1D3-4', difficulty:'1', likeability:'1'},
            {name: 'Storm', assignment: 'W1D3-5', difficulty:'2', likeability:'2'},
            {name: 'Storm', assignment: 'W1D3 - Project - Guess-the-number', difficulty:'3', likeability:'4'},
            {name: 'Storm', assignment: 'W1D4-1', difficulty:'4', likeability:'2'},
            {name: 'Storm', assignment: 'W1D4 - Project - Kleurentoggle', difficulty:'3', likeability:'2'},
            {name: 'Storm', assignment: 'W1D5 - Project -Â Galgje', difficulty:'4', likeability:'4'},
            {name: 'Storm', assignment: 'W2D1-1', difficulty:'2', likeability:'4'},
            {name: 'Storm', assignment: 'W2D1-2', difficulty:'3', likeability:'2'},
            {name: 'Storm', assignment: 'W2D2-1', difficulty:'4', likeability:'4'},
            {name: 'Storm', assignment: 'W2D2-2', difficulty:'2', likeability:'1'},
            {name: 'Storm', assignment: 'W2D2-3', difficulty:'1', likeability:'1'},
            {name: 'Storm', assignment: 'W2D3-1', difficulty:'2', likeability:'3'},
            {name: 'Storm', assignment: 'W2D3-2', difficulty:'3', likeability:'4'},
            {name: 'Storm', assignment: 'W2D3-3', difficulty:'3', likeability:'2'},
            {name: 'Storm', assignment: 'W2D4-1', difficulty:'3', likeability:'4'},
            {name: 'Storm', assignment: 'W2D4-2', difficulty:'4', likeability:'3'},
            {name: 'Storm', assignment: 'W2D4-3', difficulty:'2', likeability:'1'},
            {name: 'Storm', assignment: 'W2D5 - Project - Filmzoeker', difficulty:'4', likeability:'1'},
            {name: 'Storm', assignment: 'W3D1-1', difficulty:'2', likeability:'1'},
            {name: 'Storm', assignment: 'W3D1-2', difficulty:'2', likeability:'2'},
            {name: 'Storm', assignment: 'W3D1-3', difficulty:'1', likeability:'2'},
            {name: 'Storm', assignment: 'W3D1-4', difficulty:'2', likeability:'3'},
            {name: 'Storm', assignment: 'W3D2-1', difficulty:'1', likeability:'4'},
            {name: 'Storm', assignment: 'W3D2-2', difficulty:'3', likeability:'3'},
            {name: 'Storm', assignment: 'W3D2-3', difficulty:'3', likeability:'4'},
            {name: 'Storm', assignment: 'W3D3-1', difficulty:'3', likeability:'4'},
            {name: 'Storm', assignment: 'W3D3-2', difficulty:'1', likeability:'2'},
            {name: 'Storm', assignment: 'W3D3-3', difficulty:'3', likeability:'1'},
            {name: 'Storm', assignment: 'W3D3-4', difficulty:'3', likeability:'1'},
            {name: 'Storm', assignment: 'W3D4-1', difficulty:'2', likeability:'4'},
            {name: 'Storm', assignment: 'W3D4-2', difficulty:'3', likeability:'4'},
            {name: 'Storm', assignment: 'W3D5 - Project - Todo-List', difficulty:'3', likeability:'2'},
            {name: 'Storm', assignment: 'W4D2-1', difficulty:'2', likeability:'1'},
            {name: 'Storm', assignment: 'W4D2-2', difficulty:'3', likeability:'3'},
            {name: 'Storm', assignment: 'W4D2-3', difficulty:'2', likeability:'2'},
            {name: 'Storm', assignment: 'W4D2-4', difficulty:'3', likeability:'4'},
            {name: 'Storm', assignment: 'W4D3-1', difficulty:'3', likeability:'4'},
            {name: 'Storm', assignment: 'W4D3-2', difficulty:'2', likeability:'3'},
            {name: 'Storm', assignment: 'W4D3-3', difficulty:'1', likeability:'1'},
            {name: 'Storm', assignment: 'W4D3-4', difficulty:'3', likeability:'1'},
            {name: 'Storm', assignment: 'W4D3-5', difficulty:'2', likeability:'3'},
            {name: 'Storm', assignment: 'W4D3 - Project - Next-Level CSS', difficulty:'4', likeability:'1'},
            {name: 'Storm', assignment: 'W5D4-1', difficulty:'2', likeability:'2'},
            {name: 'Storm', assignment: 'W5D5 - Project - Lil_Playlist', difficulty:'1', likeability:'2'},
            {name: 'Storm', assignment: 'W6D1-1', difficulty:'4', likeability:'4'},
            {name: 'Storm', assignment: 'W6D2-1', difficulty:'1', likeability:'1'},
            {name: 'Storm', assignment: 'W6D2 - Project - Eindopdracht', difficulty:'3', likeability:'3'},
            
          ]      
        }
  
       
    }
    
  
    
    render(){
        return (
            <div>
            <AppHeader/>
            <AppMenu data={this.state} />

            <div style={{float:'right', marginTop:15, marginRight:11+'%'}}>
                <p style={{color:'#4a90e2'}}>Moeilijkheid</p>
                <p style={{color:'#9a4'}}>leuk</p>
            </div>
            <MainChart data={this.state}/>
            <PersonalChart data={this.state}/>
            </div>
        )
    }
}
    export default App;